FROM node:6.9

RUN mkdir /var/www

WORKDIR /var/www

RUN echo 'test' > test.txt
RUN echo 'test' > test.html
RUN echo 'test' > test.css
RUN mkdir static-assets
RUN echo 'test' > ./static-assets/test2.txt
RUN echo 'test' > ./static-assets/test2.css

RUN npm install -g http-server

EXPOSE 8000

CMD [ "http-server", "-p", "8000" ]
