version: "3"

services:
  python: 
    build:
      context: .
      dockerfile: Dockerfile.python
  node: 
    build:
      context: .
      dockerfile: Dockerfile.node

  haproxy:
    build: .
    ports:
      - "8002:8002"
    
