FROM ubuntu

RUN apt-get update
RUN apt-get -y install python
RUN apt-get clean

RUN mkdir /var/www

WORKDIR /var/www

RUN echo 'test' > test.txt

EXPOSE 8000

CMD [ "python", "-m", "SimpleHTTPServer" ]
